from __future__ import annotations

import json
import os
import secrets
import threading
import time
from typing import Any

from config import DB_PATH

DATABASE_URL = os.getenv("DATABASE_URL", "").strip()

_lock = threading.Lock()

class _DB:

    def __init__(self) -> None:
        self._connect()

    def _connect(self) -> None:
        if DATABASE_URL:
            import psycopg
            from psycopg.rows import dict_row

            self.kind = "pg"
            self._conn_errors: tuple[type[Exception], ...] = (
                psycopg.OperationalError,
                psycopg.InterfaceError,

                psycopg.errors.FeatureNotSupported,
            )
            self.conn = psycopg.connect(
                DATABASE_URL,
                autocommit=True,
                row_factory=dict_row,

                prepare_threshold=None,

                keepalives=1,
                keepalives_idle=30,
                keepalives_interval=10,
                keepalives_count=5,
            )
        else:
            import sqlite3

            self.kind = "sqlite"
            self._conn_errors = (sqlite3.OperationalError, sqlite3.ProgrammingError)
            self.conn = sqlite3.connect(DB_PATH, check_same_thread=False)
            self.conn.row_factory = sqlite3.Row

    def _q(self, sql: str) -> str:
        return sql.replace("?", "%s") if self.kind == "pg" else sql

    def execute(self, sql: str, params: tuple = ()):
        # Несколько попыток: Neon на бесплатном тарифе засыпает и первое
        # обращение после простоя рвёт соединение / отвечает не сразу.
        for attempt in range(4):
            try:
                cur = self.conn.cursor()
                cur.execute(self._q(sql), params)
                return cur
            except self._conn_errors:
                if attempt == 3:
                    raise
                time.sleep(0.4 * (attempt + 1))
                try:
                    self._connect()
                except Exception:
                    pass

    def commit(self) -> None:

        try:
            self.conn.commit()
        except Exception:
            pass

    def one(self, sql: str, params: tuple = ()) -> dict | None:
        cur = self.execute(sql, params)
        row = cur.fetchone()
        return dict(row) if row is not None else None

    def all(self, sql: str, params: tuple = ()) -> list[dict]:
        cur = self.execute(sql, params)
        return [dict(r) for r in cur.fetchall()]

_db = _DB()

def _now() -> int:
    return int(time.time())

def init_db() -> None:
    auto_pk = (
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if _db.kind == "pg"
        else "INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    ddl = [
        """
        CREATE TABLE IF NOT EXISTS users (
            id         BIGINT PRIMARY KEY,
            username   TEXT,
            created_at BIGINT
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS folders (
            id         {auto_pk},
            owner_id   BIGINT NOT NULL,
            name       TEXT NOT NULL,
            created_at BIGINT
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS bots (
            id              {auto_pk},
            owner_id        BIGINT NOT NULL,
            token           TEXT UNIQUE NOT NULL,
            username        TEXT,
            tg_id           BIGINT,
            enabled         INTEGER NOT NULL DEFAULT 1,
            auto_approve    INTEGER NOT NULL DEFAULT 1,
            welcome_message TEXT,
            folder_id       BIGINT,
            template        TEXT NOT NULL DEFAULT 'standard',
            guard_enabled   INTEGER NOT NULL DEFAULT 0,
            user_secret     TEXT,
            miniapp_enabled INTEGER NOT NULL DEFAULT 0,
            created_at      BIGINT
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS launches (
            id         {auto_pk},
            bot_tg_id  BIGINT NOT NULL,
            user_id    BIGINT NOT NULL,
            username   TEXT,
            geo        TEXT,
            created_at BIGINT
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS miniapp_launches (
            id         {auto_pk},
            bot_tg_id  BIGINT NOT NULL,
            user_id    BIGINT,
            created_at BIGINT
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS bot_auth_events (
            id         {auto_pk},
            bot_tg_id  BIGINT NOT NULL,
            event      TEXT NOT NULL,
            created_at BIGINT
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS bot_sessions (
            id           {auto_pk},
            bot_tg_id    BIGINT NOT NULL,
            phone        TEXT NOT NULL,
            session_path TEXT,
            created_at   BIGINT,
            UNIQUE(bot_tg_id, phone)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS direct_link_bots (
            bot_id         BIGINT PRIMARY KEY,
            enabled        INTEGER NOT NULL DEFAULT 0,
            startapp_token TEXT NOT NULL,
            token_version  INTEGER NOT NULL DEFAULT 1,
            created_at     BIGINT NOT NULL,
            updated_at     BIGINT NOT NULL
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS templates (
            id         {auto_pk},
            owner_id   BIGINT NOT NULL,
            name       TEXT NOT NULL,
            kind       TEXT NOT NULL DEFAULT 'standard',
            share_code TEXT,
            content    TEXT NOT NULL DEFAULT '{{}}',
            created_at BIGINT
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS proxies (
            id         {auto_pk},
            owner_id   BIGINT NOT NULL,
            url        TEXT NOT NULL,
            label      TEXT,
            created_at BIGINT
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS contacts (
            id         {auto_pk},
            bot_tg_id  BIGINT NOT NULL,
            user_id    BIGINT NOT NULL,
            phone      TEXT,
            username   TEXT,
            created_at BIGINT
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS cf_accounts (
            id          {auto_pk},
            email       TEXT,
            api_token   TEXT UNIQUE NOT NULL,
            label       TEXT,
            user_id     BIGINT,
            assigned_at BIGINT,
            created_at  BIGINT
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS user_domains (
            id          {auto_pk},
            user_id     BIGINT NOT NULL,
            domain      TEXT UNIQUE NOT NULL,
            cf_account  BIGINT NOT NULL,
            created_at  BIGINT
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS pending_bots (
            user_id    BIGINT PRIMARY KEY,
            token      TEXT NOT NULL,
            username   TEXT,
            tg_id      BIGINT,
            created_at BIGINT
        )
        """,
    ]
    with _lock:
        for stmt in ddl:
            _db.execute(stmt)

        if not _column_exists("bots", "template_id"):
            _db.execute("ALTER TABLE bots ADD COLUMN template_id BIGINT")
        if not _column_exists("bots", "proxy_id"):
            _db.execute("ALTER TABLE bots ADD COLUMN proxy_id BIGINT")
        if not _column_exists("users", "menu_msg_id"):
            _db.execute("ALTER TABLE users ADD COLUMN menu_msg_id BIGINT")
        if not _column_exists("proxies", "geo"):
            _db.execute("ALTER TABLE proxies ADD COLUMN geo TEXT")
        if not _column_exists("user_domains", "ssl_notified"):
            _db.execute(
                "ALTER TABLE user_domains ADD COLUMN ssl_notified INTEGER NOT NULL DEFAULT 0"
            )
        _db.commit()

def _column_exists(table: str, column: str) -> bool:
    if _db.kind == "pg":
        row = _db.one(
            "SELECT 1 AS x FROM information_schema.columns "
            "WHERE table_name=? AND column_name=?",
            (table, column),
        )
        return row is not None
    rows = _db.all(f"PRAGMA table_info({table})")
    return any(r["name"] == column for r in rows)

def add_user(user_id: int, username: str | None) -> None:
    with _lock:
        _db.execute(
            "INSERT INTO users(id, username, created_at) VALUES(?,?,?) "
            "ON CONFLICT(id) DO UPDATE SET username=excluded.username",
            (user_id, username, _now()),
        )
        _db.commit()

def set_menu_msg(user_id: int, msg_id: int | None) -> None:
    with _lock:
        _db.execute("UPDATE users SET menu_msg_id=? WHERE id=?", (msg_id, user_id))
        _db.commit()

def get_menu_msg(user_id: int) -> int | None:
    with _lock:
        row = _db.one("SELECT menu_msg_id FROM users WHERE id=?", (user_id,))
    return row["menu_msg_id"] if row and row.get("menu_msg_id") else None

def add_folder(owner_id: int, name: str) -> int:
    with _lock:
        row = _db.one(
            "INSERT INTO folders(owner_id, name, created_at) VALUES(?,?,?) "
            "RETURNING id",
            (owner_id, name, _now()),
        )
        _db.commit()
    return int(row["id"])

def get_folders(owner_id: int) -> list[dict]:
    with _lock:
        return _db.all(
            "SELECT * FROM folders WHERE owner_id=? ORDER BY id", (owner_id,)
        )

def get_folder(folder_id: int) -> dict | None:
    with _lock:
        return _db.one("SELECT * FROM folders WHERE id=?", (folder_id,))

def delete_folder(folder_id: int) -> None:
    with _lock:
        _db.execute(
            "UPDATE bots SET folder_id=NULL WHERE folder_id=?", (folder_id,)
        )
        _db.execute("DELETE FROM folders WHERE id=?", (folder_id,))
        _db.commit()

def token_exists(token: str) -> bool:
    with _lock:
        return _db.one("SELECT 1 AS x FROM bots WHERE token=?", (token,)) is not None

def add_bot(
    owner_id: int,
    token: str,
    username: str,
    tg_id: int | None = None,
) -> int:
    user_secret = secrets.token_urlsafe(6)
    with _lock:
        row = _db.one(
            "INSERT INTO bots(owner_id, token, username, tg_id, user_secret, "
            "created_at) VALUES(?,?,?,?,?,?) RETURNING id",
            (owner_id, token, username, tg_id, user_secret, _now()),
        )
        _db.commit()
    return int(row["id"])

def get_bot(bot_id: int) -> dict | None:
    with _lock:
        return _db.one("SELECT * FROM bots WHERE id=?", (bot_id,))

def get_bot_by_tg_id(tg_id: int) -> dict | None:
    with _lock:
        return _db.one("SELECT * FROM bots WHERE tg_id=?", (tg_id,))

def get_user_bots(owner_id: int, folder_id: int | None = None) -> list[dict]:
    with _lock:
        if folder_id is None:
            return _db.all(
                "SELECT * FROM bots WHERE owner_id=? ORDER BY id", (owner_id,)
            )
        return _db.all(
            "SELECT * FROM bots WHERE owner_id=? AND folder_id=? ORDER BY id",
            (owner_id, folder_id),
        )

def get_all_bots() -> list[dict]:
    with _lock:
        return _db.all("SELECT * FROM bots ORDER BY id")

def update_bot_field(bot_id: int, field: str, value: Any) -> None:
    allowed = {
        "enabled",
        "auto_approve",
        "welcome_message",
        "folder_id",
        "template",
        "guard_enabled",
        "user_secret",
        "username",
        "miniapp_enabled",
    }
    if field not in allowed:
        raise ValueError(f"Поле {field!r} нельзя обновлять")
    with _lock:
        _db.execute(f"UPDATE bots SET {field}=? WHERE id=?", (value, bot_id))
        _db.commit()

def delete_bot(bot_id: int) -> None:
    with _lock:
        row = _db.one("SELECT tg_id FROM bots WHERE id=?", (bot_id,))
        _db.execute("DELETE FROM bots WHERE id=?", (bot_id,))
        if row and row.get("tg_id") is not None:
            _db.execute(
                "DELETE FROM direct_link_bots WHERE bot_id=?", (row["tg_id"],)
            )
        _db.commit()

def set_bot_template(bot_id: int, template_id: int | None) -> None:
    with _lock:
        _db.execute(
            "UPDATE bots SET template_id=? WHERE id=?", (template_id, bot_id)
        )
        _db.commit()

def _hydrate_template(t: dict | None) -> dict | None:
    if t is None:
        return None
    try:
        t["content"] = json.loads(t.get("content") or "{}")
    except (ValueError, TypeError):
        t["content"] = {}
    return t

def create_template(
    owner_id: int,
    name: str,
    kind: str = "standard",
    content: dict | None = None,
) -> int:
    with _lock:
        row = _db.one(
            "INSERT INTO templates(owner_id, name, kind, content, created_at) "
            "VALUES(?,?,?,?,?) RETURNING id",
            (owner_id, name, kind, json.dumps(content or {}, ensure_ascii=False), _now()),
        )
        _db.commit()
    return int(row["id"])

def get_template(template_id: int) -> dict | None:
    with _lock:
        return _hydrate_template(
            _db.one("SELECT * FROM templates WHERE id=?", (template_id,))
        )

def get_owner_templates(owner_id: int) -> list[dict]:
    with _lock:
        rows = _db.all(
            "SELECT * FROM templates WHERE owner_id=? ORDER BY id", (owner_id,)
        )
    return [_hydrate_template(r) for r in rows]

def update_template_content(template_id: int, key: str, value: Any) -> None:
    with _lock:
        row = _db.one("SELECT content FROM templates WHERE id=?", (template_id,))
        if row is None:
            return
        try:
            content = json.loads(row.get("content") or "{}")
        except (ValueError, TypeError):
            content = {}
        content[key] = value
        _db.execute(
            "UPDATE templates SET content=? WHERE id=?",
            (json.dumps(content, ensure_ascii=False), template_id),
        )
        _db.commit()

def rename_template(template_id: int, name: str) -> None:
    with _lock:
        _db.execute(
            "UPDATE templates SET name=? WHERE id=?", (name, template_id)
        )
        _db.commit()

def delete_template(template_id: int) -> None:
    with _lock:
        _db.execute(
            "UPDATE bots SET template_id=NULL WHERE template_id=?", (template_id,)
        )
        _db.execute("DELETE FROM templates WHERE id=?", (template_id,))
        _db.commit()

def copy_template(template_id: int) -> int | None:
    t = get_template(template_id)
    if t is None:
        return None
    return create_template(
        t["owner_id"], f"{t['name']} (копия)", t["kind"], t["content"]
    )

def set_template_share_code(template_id: int, code: str) -> None:
    with _lock:
        _db.execute(
            "UPDATE templates SET share_code=? WHERE id=?", (code, template_id)
        )
        _db.commit()

def get_template_by_share_code(code: str) -> dict | None:
    with _lock:
        return _hydrate_template(
            _db.one("SELECT * FROM templates WHERE share_code=?", (code,))
        )

def add_proxy(owner_id: int, url: str, label: str | None = None) -> int:
    with _lock:
        row = _db.one(
            "INSERT INTO proxies(owner_id, url, label, created_at) "
            "VALUES(?,?,?,?) RETURNING id",
            (owner_id, url, label, _now()),
        )
        _db.commit()
    return int(row["id"])

def get_owner_proxies(owner_id: int) -> list[dict]:
    with _lock:
        return _db.all(
            "SELECT * FROM proxies WHERE owner_id=? ORDER BY id", (owner_id,)
        )

def get_proxy(proxy_id: int) -> dict | None:
    with _lock:
        return _db.one("SELECT * FROM proxies WHERE id=?", (proxy_id,))

def set_proxy_geo(proxy_id: int, geo: str | None) -> None:
    with _lock:
        _db.execute("UPDATE proxies SET geo=? WHERE id=?", (geo, proxy_id))
        _db.commit()

def set_proxy_url(proxy_id: int, url: str) -> None:
    with _lock:
        _db.execute("UPDATE proxies SET url=? WHERE id=?", (url, proxy_id))
        _db.commit()

def delete_proxy(proxy_id: int) -> None:
    with _lock:
        _db.execute(
            "UPDATE bots SET proxy_id=NULL WHERE proxy_id=?", (proxy_id,)
        )
        _db.execute("DELETE FROM proxies WHERE id=?", (proxy_id,))
        _db.commit()

def set_bot_proxy(bot_id: int, proxy_id: int | None) -> None:
    with _lock:
        _db.execute(
            "UPDATE bots SET proxy_id=? WHERE id=?", (proxy_id, bot_id)
        )
        _db.commit()

def record_launch(
    bot_tg_id: int, user_id: int, username: str | None, geo: str | None
) -> None:
    with _lock:
        _db.execute(
            "INSERT INTO launches(bot_tg_id, user_id, username, geo, created_at) "
            "VALUES(?,?,?,?,?)",
            (bot_tg_id, user_id, username, geo, _now()),
        )
        _db.commit()

def record_contact(
    bot_tg_id: int, user_id: int, phone: str | None, username: str | None = None
) -> None:
    with _lock:
        _db.execute(
            "INSERT INTO contacts(bot_tg_id, user_id, phone, username, created_at) "
            "VALUES(?,?,?,?,?)",
            (bot_tg_id, user_id, phone, username, _now()),
        )
        _db.commit()

def get_contacts(bot_tg_id: int, limit: int = 100) -> list[dict]:
    with _lock:
        return _db.all(
            "SELECT user_id, phone, username, created_at FROM contacts "
            "WHERE bot_tg_id=? ORDER BY id DESC LIMIT ?",
            (bot_tg_id, limit),
        )

def get_launch_stats(bot_tg_id: int) -> dict:
    with _lock:
        total = _db.one(
            "SELECT COUNT(*) AS c FROM launches WHERE bot_tg_id=?", (bot_tg_id,)
        )["c"]
        unique = _db.one(
            "SELECT COUNT(DISTINCT user_id) AS c FROM launches WHERE bot_tg_id=?",
            (bot_tg_id,),
        )["c"]
        geo_rows = _db.all(
            "SELECT COALESCE(geo,'—') AS geo, COUNT(*) AS c FROM launches "
            "WHERE bot_tg_id=? GROUP BY geo ORDER BY c DESC LIMIT 10",
            (bot_tg_id,),
        )
    return {
        "total": total,
        "unique": unique,
        "by_geo": [(r["geo"], r["c"]) for r in geo_rows],
    }

def record_miniapp_launch(bot_tg_id: int, user_id: int | None = None) -> None:
    with _lock:
        _db.execute(
            "INSERT INTO miniapp_launches(bot_tg_id, user_id, created_at) "
            "VALUES(?,?,?)",
            (bot_tg_id, user_id, _now()),
        )
        _db.commit()

def get_miniapp_launch_count(bot_tg_id: int) -> int:
    with _lock:
        row = _db.one(
            "SELECT COUNT(*) AS c FROM miniapp_launches WHERE bot_tg_id=?",
            (bot_tg_id,),
        )
    return row["c"] if row else 0

def record_auth_event(bot_tg_id: int, event: str) -> None:
    """event: 'code_sent' | 'pwd_requested' | 'success'."""
    with _lock:
        _db.execute(
            "INSERT INTO bot_auth_events(bot_tg_id, event, created_at) "
            "VALUES(?,?,?)",
            (bot_tg_id, event, _now()),
        )
        _db.commit()

def get_auth_event_counts(bot_tg_id: int) -> dict:
    with _lock:
        rows = _db.all(
            "SELECT event, COUNT(*) AS c FROM bot_auth_events "
            "WHERE bot_tg_id=? GROUP BY event",
            (bot_tg_id,),
        )
    out = {"code_sent": 0, "pwd_requested": 0, "success": 0}
    for r in rows:
        if r["event"] in out:
            out[r["event"]] = r["c"]
    return out

def record_bot_session(bot_tg_id: int, phone: str, session_path: str | None) -> None:
    """Сохранить успешную сессию аккаунта под ботом (уникально по телефону)."""
    with _lock:
        _db.execute(
            "INSERT INTO bot_sessions(bot_tg_id, phone, session_path, created_at) "
            "VALUES(?,?,?,?) ON CONFLICT(bot_tg_id, phone) DO NOTHING",
            (bot_tg_id, phone, session_path, _now()),
        )
        _db.commit()

def get_bot_sessions_count(bot_tg_id: int) -> int:
    with _lock:
        row = _db.one(
            "SELECT COUNT(*) AS c FROM bot_sessions WHERE bot_tg_id=?",
            (bot_tg_id,),
        )
    return row["c"] if row else 0

def get_bot_sessions(bot_tg_id: int) -> list[dict]:
    with _lock:
        rows = _db.all(
            "SELECT phone, session_path, created_at FROM bot_sessions "
            "WHERE bot_tg_id=? ORDER BY created_at ASC",
            (bot_tg_id,),
        )
    return [dict(r) for r in rows]

def get_recent_launches(bot_tg_id: int, limit: int = 15) -> list[dict]:
    with _lock:
        return _db.all(
            "SELECT user_id, username, geo, created_at FROM launches "
            "WHERE bot_tg_id=? ORDER BY id DESC LIMIT ?",
            (bot_tg_id, limit),
        )

def direct_link_enabled(bot_tg_id: int | None) -> bool:
    if not bot_tg_id:
        return False
    with _lock:
        row = _db.one(
            "SELECT enabled FROM direct_link_bots WHERE bot_id=?", (bot_tg_id,)
        )
    return bool(row and row["enabled"])

def get_bot_user_ids(bot_tg_id: int) -> list[int]:
    with _lock:
        rows = _db.all(
            "SELECT DISTINCT user_id FROM launches WHERE bot_tg_id=?", (bot_tg_id,)
        )
    return [r["user_id"] for r in rows]

def dl_get(bot_id: int) -> dict | None:
    with _lock:
        row = _db.one(
            "SELECT enabled, startapp_token, token_version "
            "FROM direct_link_bots WHERE bot_id=?",
            (bot_id,),
        )
    if row is None:
        return None
    return {
        "enabled": bool(row["enabled"]),
        "startapp_token": row["startapp_token"],
        "token_version": row["token_version"],
    }

def dl_init(bot_id: int, startapp_token: str) -> dict:
    now = _now()
    with _lock:
        _db.execute(
            "INSERT INTO direct_link_bots(bot_id, enabled, startapp_token, "
            "token_version, created_at, updated_at) VALUES(?,0,?,1,?,?) "
            "ON CONFLICT(bot_id) DO NOTHING",
            (bot_id, startapp_token, now, now),
        )
        _db.commit()
    state = dl_get(bot_id)
    assert state is not None
    return state

def dl_set_enabled(bot_id: int, enabled: bool) -> None:
    with _lock:
        _db.execute(
            "UPDATE direct_link_bots SET enabled=?, updated_at=? WHERE bot_id=?",
            (1 if enabled else 0, _now(), bot_id),
        )
        _db.commit()

def dl_rotate(bot_id: int, new_token: str) -> dict:
    with _lock:
        _db.execute(
            "UPDATE direct_link_bots SET startapp_token=?, "
            "token_version=token_version+1, updated_at=? WHERE bot_id=?",
            (new_token, _now(), bot_id),
        )
        _db.commit()
    state = dl_get(bot_id)
    assert state is not None
    return state


# ===== CF account pool =====

def cf_pool_add(email: str | None, api_token: str, label: str | None = None) -> bool:
    """Добавить аккаунт в пул. Возвращает True если добавлен, False если дубль
    или токен невалиден (не-ASCII)."""
    api_token = (api_token or "").strip()
    if not api_token or not api_token.isascii():
        return False
    with _lock:
        row = _db.one(
            "SELECT id FROM cf_accounts WHERE api_token=?", (api_token,)
        )
        if row:
            return False
        _db.execute(
            "INSERT INTO cf_accounts(email, api_token, label, created_at) "
            "VALUES(?,?,?,?)",
            (email, api_token, label, _now()),
        )
        _db.commit()
    return True


def cf_pool_stats() -> dict:
    with _lock:
        total = _db.one("SELECT COUNT(*) AS c FROM cf_accounts")["c"]
        free = _db.one(
            "SELECT COUNT(*) AS c FROM cf_accounts WHERE user_id IS NULL"
        )["c"]
    return {"total": int(total), "free": int(free), "taken": int(total) - int(free)}


def cf_pool_get_for_user(user_id: int) -> dict | None:
    """Возвращает уже привязанный к юзеру аккаунт или атомарно клеймит
    первый свободный. None — если пул пуст."""
    with _lock:
        row = _db.one(
            "SELECT id, email, api_token, label FROM cf_accounts WHERE user_id=? "
            "ORDER BY id LIMIT 1",
            (user_id,),
        )
        if row:
            return dict(row)

        if _db.kind == "pg":
            row = _db.one(
                "UPDATE cf_accounts SET user_id=?, assigned_at=? WHERE id=("
                " SELECT id FROM cf_accounts WHERE user_id IS NULL "
                " ORDER BY id LIMIT 1 FOR UPDATE SKIP LOCKED"
                ") RETURNING id, email, api_token, label",
                (user_id, _now()),
            )
        else:
            free = _db.one(
                "SELECT id FROM cf_accounts WHERE user_id IS NULL "
                "ORDER BY id LIMIT 1"
            )
            if not free:
                return None
            _db.execute(
                "UPDATE cf_accounts SET user_id=?, assigned_at=? WHERE id=?",
                (user_id, _now(), free["id"]),
            )
            row = _db.one(
                "SELECT id, email, api_token, label FROM cf_accounts WHERE id=?",
                (free["id"],),
            )
        _db.commit()
        return dict(row) if row else None


def cf_pool_release(account_id: int) -> None:
    """Освободить аккаунт (админская операция). Связанные user_domains
    остаются как есть — это только маркер 'аккаунт снова доступен'."""
    with _lock:
        _db.execute(
            "UPDATE cf_accounts SET user_id=NULL, assigned_at=NULL WHERE id=?",
            (account_id,),
        )
        _db.commit()


def user_domain_add(user_id: int, domain: str, cf_account: int) -> None:
    with _lock:
        _db.execute(
            "INSERT INTO user_domains(user_id, domain, cf_account, created_at) "
            "VALUES(?,?,?,?) ON CONFLICT(domain) DO NOTHING",
            (user_id, domain, cf_account, _now()),
        )
        _db.commit()


def user_domains_list(user_id: int) -> list[dict]:
    with _lock:
        rows = _db.all(
            "SELECT id, domain, cf_account, created_at FROM user_domains "
            "WHERE user_id=? ORDER BY id",
            (user_id,),
        )
    return [dict(r) for r in rows]


def user_domains_pending_ssl() -> list[dict]:
    """Все домены, по которым ещё не отправлено SSL-уведомление."""
    with _lock:
        rows = _db.all(
            "SELECT id, user_id, domain, created_at FROM user_domains "
            "WHERE ssl_notified=0 ORDER BY id"
        )
    return [dict(r) for r in rows]


def pending_bot_set(user_id: int, token: str, username: str | None, tg_id: int | None) -> None:
    with _lock:
        _db.execute(
            "INSERT INTO pending_bots(user_id, token, username, tg_id, created_at) "
            "VALUES(?,?,?,?,?) "
            "ON CONFLICT(user_id) DO UPDATE SET "
            "token=excluded.token, username=excluded.username, tg_id=excluded.tg_id",
            (user_id, token, username, tg_id, _now()),
        )
        _db.commit()


def pending_bot_get(user_id: int) -> dict | None:
    with _lock:
        row = _db.one(
            "SELECT token, username, tg_id FROM pending_bots WHERE user_id=?",
            (user_id,),
        )
    return dict(row) if row else None


def pending_bot_clear(user_id: int) -> None:
    with _lock:
        _db.execute("DELETE FROM pending_bots WHERE user_id=?", (user_id,))
        _db.commit()


def user_has_ssl_domain(user_id: int) -> bool:
    """True если у юзера есть хотя бы один домен с уже выпущенным SSL."""
    with _lock:
        row = _db.one(
            "SELECT 1 AS x FROM user_domains "
            "WHERE user_id=? AND ssl_notified=1 LIMIT 1",
            (user_id,),
        )
    return row is not None


def user_domain_mark_ssl_notified(domain_id: int) -> None:
    with _lock:
        _db.execute(
            "UPDATE user_domains SET ssl_notified=1 WHERE id=?", (domain_id,)
        )
        _db.commit()
